@echo off

echo ========================================
echo      TA Processing Tool - Build Tool
echo ========================================
echo Mulai kompilasi dengan Nuitka...

python -m nuitka ^
--standalone ^
--jobs=10 ^
--show-progress ^
--msvc=latest ^
--windows-icon-from-ico=HFH.ico ^
--assume-yes-for-downloads ^
--output-filename="TA Processing Tool.exe" ^
--include-data-file=HFH.ico=HFH.ico ^
--windows-console-mode=disable ^
--include-module=google.oauth2.service_account ^
--include-module=google.auth.transport.requests ^
--include-module=google.api_core ^
--include-module=google.auth ^
--include-module=googleapiclient ^
--include-module=requests ^
--include-module=wmi ^
--include-module=pandas ^
--include-module=numpy ^
--include-module=dearpygui ^
--include-module=pathlib ^
--enable-plugin=tk-inter ^
--enable-plugin=implicit-imports ^
--output-dir=dist ^
--lto=no ^
--nofollow-import-to=matplotlib ^
--nofollow-import-to=scikit-learn ^
--nofollow-import-to=tensorflow ^
--nofollow-import-to=torch ^
--nofollow-import-to=jupyter ^
--nofollow-import-to=pytest ^
--nofollow-import-to=unittest ^
--include-module=sqlalchemy ^
--include-module=pymysql ^
--nofollow-import-to=cx_Oracle ^
--nofollow-import-to=opencv-python ^
--nofollow-import-to=geopandas ^
--nofollow-import-to=networkx ^
--nofollow-import-to=pycryptodome ^
--nofollow-import-to=cryptography ^
--nofollow-import-to=flask ^
--nofollow-import-to=fonttools ^
--nofollow-import-to=geopy ^
--nofollow-import-to=ipython ^
--nofollow-import-to=mitmproxy ^
--nofollow-import-to=pyarmor ^
--nofollow-import-to=simplekml ^
--nofollow-import-to=tabulate ^
--nofollow-import-to=wikipedia ^
--nofollow-import-to=aioquic ^
--nofollow-import-to=beautifulsoup4 ^
--nofollow-import-to=black ^
--nofollow-import-to=shapely ^
--nofollow-import-to=pyarrow ^
--nofollow-import-to=pyOpenSSL ^
--nofollow-import-to=jupyter_client ^
--nofollow-import-to=jupyter_core ^
--nofollow-import-to=nbconvert ^
--nofollow-import-to=nbformat ^
--nofollow-import-to=pillow ^
--nofollow-import-to=PyMuPDF ^
--nofollow-import-to=PyPDF2 ^
--nofollow-import-to=tornado ^
--nofollow-import-to=scipy ^
--nofollow-import-to=plotly ^
--nofollow-import-to=seaborn ^
--nofollow-import-to=bokeh ^
--nofollow-import-to=altair ^
--nofollow-import-to=openpyxl ^
--nofollow-import-to=xlrd ^
--nofollow-import-to=xlwt ^
--nofollow-import-to=xlsxwriter ^
--nofollow-import-to=django ^
--nofollow-import-to=fastapi ^
--nofollow-import-to=starlette ^
--nofollow-import-to=uvicorn ^
--nofollow-import-to=pydantic ^
--nofollow-import-to=pymongo ^
--nofollow-import-to=redis ^
--nofollow-import-to=celery ^
--nofollow-import-to=dask ^
--nofollow-import-to=pyodbc ^
--nofollow-import-to=h5py ^
--nofollow-import-to=tables ^
--nofollow-import-to=parquet ^
--nofollow-import-to=feather ^
--nofollow-import-to=statsmodels ^
--nofollow-import-to=sympy ^
--nofollow-import-to=numba ^
--nofollow-import-to=cython ^
--nofollow-import-to=pyinstaller ^
--nofollow-import-to=cx_Freeze ^
--nofollow-import-to=py2exe ^
--nofollow-import-to=auto-py-to-exe ^
--nofollow-import-to=kivy ^
--nofollow-import-to=pygame ^
--nofollow-import-to=pyglet ^
--nofollow-import-to=pyside2 ^
--nofollow-import-to=pyside6 ^
--nofollow-import-to=pyqt5 ^
--nofollow-import-to=pyqt6 ^
--nofollow-import-to=wxpython ^
--nofollow-import-to=streamlit ^
--nofollow-import-to=dash ^
--nofollow-import-to=gradio ^
--nofollow-import-to=folium ^
--nofollow-import-to=branca ^
--nofollow-import-to=scrapy ^
--nofollow-import-to=selenium ^
--nofollow-import-to=webdriver ^
--nofollow-import-to=playwright ^
--nofollow-import-to=httpx ^
--nofollow-import-to=aiohttp ^
--nofollow-import-to=paramiko ^
--nofollow-import-to=fabric ^
--nofollow-import-to=ansible ^
--nofollow-import-to=docker ^
--nofollow-import-to=kubernetes ^
--nofollow-import-to=boto3 ^
--nofollow-import-to=azure ^
--nofollow-import-to=google-cloud ^
--nofollow-import-to=tweepy ^
--nofollow-import-to=discord ^
--nofollow-import-to=slack ^
--nofollow-import-to=telegram ^
--nofollow-import-to=whatsapp ^
--nofollow-import-to=opencv ^
--nofollow-import-to=cv2 ^
--nofollow-import-to=imageio ^
--nofollow-import-to=skimage ^
--nofollow-import-to=lxml ^
--nofollow-import-to=html5lib ^
--nofollow-import-to=markdown ^
--nofollow-import-to=jinja2 ^
--nofollow-import-to=mako ^
--nofollow-import-to=click ^
--nofollow-import-to=fire ^
--nofollow-import-to=yaml ^
--nofollow-import-to=toml ^
--nofollow-import-to=pyyaml ^
--nofollow-import-to=ruamel ^
ta_gui.py

echo Kompilasi selesai, lanjut menjalankan Inno Setup...

:: Jalankan setup.iss dengan Inno Setup Compiler (pastikan iscc.exe ada di PATH atau beri path lengkap)
iscc setup.iss

echo Selesai semuanya.
pause
